using System.Text;

namespace Blazor.ThreeJS.Emitter.Emit;

/// <summary>
/// Collects every judgement call the emitter made, and renders them as a committed markdown file.
/// The numeric section is the point: TypeScript erases <c>int</c> and <c>float</c> to one type, so
/// most numeric members are typed by a project-wide default rather than by the upstream docs, and
/// across 309 classes that has to be reviewable rather than implicit.
/// </summary>
internal sealed class EmissionAudit
{
	private readonly List<NumericAuditEntry> _numericEntries = [];
	private readonly List<SkippedMemberEntry> _skippedMembers = [];
	private readonly NumericAuditScope _scope;

	/// <summary>Numeric decisions recorded so far, so a projection run can hand its rows to the main audit.</summary>
	public IReadOnlyList<NumericAuditEntry> NumericEntries
	{
		get { return _numericEntries; }
	}

	/// <summary>Creates an audit collecting decisions at one scope.</summary>
	/// <param name="scope">Whether these decisions reach generated code or are only a projection.</param>
	public EmissionAudit(NumericAuditScope scope = NumericAuditScope.Emitted)
	{
		_scope = scope;
	}

	/// <summary>Records how one numeric member was typed.</summary>
	/// <param name="className">Three.js class the member belongs to.</param>
	/// <param name="file">Declaring file, relative to the types package root.</param>
	/// <param name="memberName">Parameter or property name.</param>
	/// <param name="resolution">The decision and its basis.</param>
	public void RecordNumeric(string className, string file, string memberName, NumericResolution resolution)
	{
		_numericEntries.Add(new NumericAuditEntry
		{
			ClassName = className,
			File = file,
			MemberName = memberName,
			Resolution = resolution,
			Scope = _scope
		});
	}

	/// <summary>
	/// Takes over numeric decisions recorded by a projection run, so classes the emitter could emit
	/// today but has not been asked to yet still get their typing calls reviewed.
	/// </summary>
	/// <param name="entries">Rows to adopt.</param>
	public void AdoptNumerics(IEnumerable<NumericAuditEntry> entries)
	{
		_numericEntries.AddRange(entries);
	}

	/// <summary>Records a member present in three.js but absent from the generated class.</summary>
	/// <param name="className">Three.js class the member belongs to.</param>
	/// <param name="memberDescription">The member, e.g. <c>property parameters</c>.</param>
	/// <param name="reason">Why it was left out.</param>
	public void RecordSkippedMember(string className, string memberDescription, string reason)
	{
		_skippedMembers.Add(new SkippedMemberEntry
		{
			ClassName = className,
			MemberDescription = memberDescription,
			Reason = reason
		});
	}

	/// <summary>
	/// Renders the audit. Rows are sorted so the file only moves when a decision actually changes.
	/// </summary>
	/// <param name="emittedClassNames">Classes that were emitted for real, as opposed to only projected.</param>
	/// <param name="typesVersion">Version of <c>@types/three</c> the IR was extracted from.</param>
	/// <returns>Markdown, LF-terminated.</returns>
	public string Render(IReadOnlyList<string> emittedClassNames, string typesVersion)
	{
		var builder = new StringBuilder();
		AppendLine(builder, "# Emitter audit");
		AppendLine(builder);
		AppendLine(builder, $"Generated by `generator/emitter` from `generator/three-api.json` (`@types/three@{typesVersion}`).");
		AppendLine(builder, "Re-run `npm run emit` to refresh. Every row is a decision the IR did not make for the emitter.");
		AppendLine(builder);
		AppendLine(builder, $"Emitted classes: {string.Join(", ", emittedClassNames.Select(x => $"`{x}`"))}.");
		AppendLine(builder);
		AppendLine(builder, "Which classes can be emitted at all, and what happens to every member three.js declares, lives in");
		AppendLine(builder, "`generator/api-coverage.md`. This file covers only the decisions behind the code that is emitted.");
		AppendLine(builder);
		var hybridNames = string.Join(", ", EmitterConfig.HybridClassNames.Order(StringComparer.Ordinal).Select(x => $"`{x}`"));
		AppendLine(builder, $"⚠️ **The generated half of a hybrid class contributes no rows.** {hybridNames} is hand-written, and the command");
		AppendLine(builder, "and query surface emitted as the other half of its `partial class` goes through its own entry point -");
		AppendLine(builder, "one that is not handed this audit. So those members' numeric typings and skips are absent from both");
		AppendLine(builder, "sections below, and every count in them is of the emitted classes only. `generator/api-coverage.md` does");
		AppendLine(builder, "classify them, including which half of the partial each one landed on.");
		AppendLine(builder);

		AppendNumericPolicy(builder);
		AppendNumericSection(builder);
		AppendSkippedSection(builder);

		return builder.ToString();
	}

	private static void AppendNumericPolicy(StringBuilder builder)
	{
		AppendLine(builder, "## How a `number` becomes a C# type");
		AppendLine(builder);
		AppendLine(builder, "TypeScript erases integers and floats to `number`. The IR carries a kind only where the upstream");
		AppendLine(builder, "JSDoc states one, so the rest is decided here, in this order:");
		AppendLine(builder);
		AppendLine(builder, "1. **documented** — the JSDoc says ``Expects a `Float` `` or ``Expects a `Integer` ``. Taken as written.");
		AppendLine(builder, "2. **name heuristic** — unspecified, but the name ends in `Segments`, `Count` or `Index`, or is exactly");
		AppendLine(builder, "   `count` / `index`. Overridden to `int`. The match is case-insensitive, so a bare `segments`");
		AppendLine(builder, "   (`CircleGeometry`, `RingGeometry`) is caught as well as `widthSegments`.");
		AppendLine(builder, "3. **default** — unspecified and not an integer name, so `float`, because three.js is a graphics library");
		AppendLine(builder, "   and WebGL is float32 throughout.");
		AppendLine(builder);
		AppendLine(builder, "Rows 2 and 3 are inferences. They are listed individually below so they can be reviewed rather than trusted.");
		AppendLine(builder);
	}

	private void AppendNumericSection(StringBuilder builder)
	{
		var sorted = _numericEntries
			.OrderBy(x => x.ClassName, StringComparer.Ordinal)
			.ThenBy(x => x.MemberName, StringComparer.Ordinal)
			.ToList();

		AppendLine(builder, "## Numeric decisions");
		AppendLine(builder);
		AppendLine(builder, "`generated` rows are in code today. `projected` rows belong to classes the emitter could already");
		AppendLine(builder, "emit but has not been asked to — they are listed so the typing calls are reviewed before the full run,");
		AppendLine(builder, "not after.");
		AppendLine(builder);
		AppendLine(builder, "| basis | generated | projected |");
		AppendLine(builder, "|---|---|---|");
		foreach (var basis in Enum.GetValues<NumericBasis>())
		{
			var generatedCount = sorted.Count(x => x.Resolution.Basis == basis && x.Scope == NumericAuditScope.Emitted);
			var projectedCount = sorted.Count(x => x.Resolution.Basis == basis && x.Scope == NumericAuditScope.Projected);
			AppendLine(builder, $"| {DescribeBasis(basis)} | {generatedCount} | {projectedCount} |");
		}

		AppendLine(builder);

		var inferred = sorted
			.Where(x => x.Resolution.IsInferred)
			.ToList();

		AppendLine(builder, $"### Inferred — review these ({inferred.Count})");
		AppendLine(builder);
		AppendLine(builder, "Every numeric the upstream JSDoc did not type, and what the emitter decided instead.");
		AppendLine(builder);
		if (inferred.Count == 0)
		{
			AppendLine(builder, "None.");
			AppendLine(builder);
		}
		else
		{
			AppendTable(builder, inferred);
		}

		var documented = sorted
			.Where(x => !x.Resolution.IsInferred)
			.ToList();

		AppendLine(builder, $"### Documented upstream — taken as written ({documented.Count})");
		AppendLine(builder);
		if (documented.Count == 0)
		{
			AppendLine(builder, "None.");
			AppendLine(builder);
			return;
		}

		AppendTable(builder, documented);
	}

	private static void AppendTable(StringBuilder builder, List<NumericAuditEntry> entries)
	{
		AppendLine(builder, "| class | member | C# type | basis | scope | file |");
		AppendLine(builder, "|---|---|---|---|---|---|");
		foreach (var entry in entries)
		{
			var scope = entry.Scope == NumericAuditScope.Emitted ? "generated" : "projected";
			AppendLine(builder, $"| `{entry.ClassName}` | `{entry.MemberName}` | `{entry.Resolution.CSharpTypeName}` | {DescribeBasis(entry.Resolution.Basis)} | {scope} | `{entry.File}` |");
		}

		AppendLine(builder);
	}

	private void AppendSkippedSection(StringBuilder builder)
	{
		AppendLine(builder, "## Members present in three.js but absent from the generated class");
		AppendLine(builder);
		if (_skippedMembers.Count == 0)
		{
			AppendLine(builder, "None.");
			AppendLine(builder);
			return;
		}

		AppendLine(builder, "| class | member | why |");
		AppendLine(builder, "|---|---|---|");
		var sorted = _skippedMembers
			.OrderBy(x => x.ClassName, StringComparer.Ordinal)
			.ThenBy(x => x.MemberDescription, StringComparer.Ordinal);

		foreach (var entry in sorted)
		{
			AppendLine(builder, $"| `{entry.ClassName}` | `{entry.MemberDescription}` | {entry.Reason} |");
		}

		AppendLine(builder);
	}

	private static string DescribeBasis(NumericBasis basis)
	{
		return basis switch
		{
			NumericBasis.DocumentedFloat => "documented `Float`",
			NumericBasis.DocumentedInteger => "documented `Integer`",
			NumericBasis.NameHeuristicInteger => "**heuristic override to `int`**",
			NumericBasis.DefaultedFloat => "**defaulted to `float`**",
			_ => throw new NotImplementedException($"Unhandled {nameof(NumericBasis)} '{basis}'.")
		};
	}

	private static void AppendLine(StringBuilder builder, string text = "")
	{
		builder.Append(text);
		builder.Append('\n');
	}
}

/// <summary>One numeric typing decision.</summary>
internal sealed class NumericAuditEntry
{
	/// <summary>Three.js class the member belongs to.</summary>
	public required string ClassName { get; init; }

	/// <summary>Declaring file, relative to the types package root.</summary>
	public required string File { get; init; }

	/// <summary>Parameter or property name.</summary>
	public required string MemberName { get; init; }

	/// <summary>The decision and its basis.</summary>
	public required NumericResolution Resolution { get; init; }

	/// <summary>Whether this decision reaches generated code today.</summary>
	public required NumericAuditScope Scope { get; init; }
}

/// <summary>Whether an audited decision is in generated code or only projected ahead of the full run.</summary>
internal enum NumericAuditScope : byte
{
	/// <summary>The decision is in a committed generated file.</summary>
	Emitted,

	/// <summary>The class emits cleanly but is not on the allowlist yet.</summary>
	Projected
}

/// <summary>One member left out of a generated class.</summary>
internal sealed class SkippedMemberEntry
{
	/// <summary>Three.js class the member belongs to.</summary>
	public required string ClassName { get; init; }

	/// <summary>The member, e.g. <c>property parameters</c>.</summary>
	public required string MemberDescription { get; init; }

	/// <summary>Why it was left out.</summary>
	public required string Reason { get; init; }
}

